[workspace]
authors = ["Filip J. Baran <filip.baran@doctoral.uj.edu.pl>"]
channels = ["conda-forge"]
name = "SciCompPy"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.3,<3.15"
numpy = ">=2.4.3,<3"
